on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'environment'
        required: true
        type: choice
        options:
            - staging
            - deploy
permissions:
  actions: write
  checks: write
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install mkdocs
      - run: pip install mkdocs-material
      - run: pip install mkdocs-material-extensions
      - run: pip install plantuml_markdown
      - run: pip install mkdocs-git-revision-date-plugin
      - run: mkdocs build
      - name: deploy
        if: "${{ github.event.inputs.environment == 'deploy' }}"
        run: mkdocs gh-deploy --force